### ISSUE TITLE
Error 404 Refresh

### ISSUE THREAD

**Issue by finishet** [creativetimofficial/vue-material-dashboard-laravel#14] opened 2022-01-31 13:53 UTC
If im on /login or any page if i refresh (f5) juts show error page 404: not found, instead of taking me to the beginning.So i need remove  / path at url for return.
Any idea what is happening?

Node Version : 16.13.2
NPM Version: 8.1.2
PHP Version : 7.4

**Comment by teamupdivision** [comment] 2022-02-04 14:29
Hi @finishet,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you send to us a screenshot or video recording with the steps and the 404 error, please? We were not able to reproduce the error and it will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2022-03-29 13:34
Hi @finishet,

Hope the issue was solved. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed by teamupdivision** 2022-03-29 13:34 UTC
